name: deploy-cloudflare-worker

on:
  push:
  workflow_dispatch:

concurrency:
  group: deploy-cloudflare-worker-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun

      - name: Build site
        run: bun run build
        working-directory: site/
      - name: Upload site build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          include-hidden-files: true
          path: site/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: cloudflare-worker/${{ github.ref_name }}
      url: ${{ steps.deploy-cloudflare-worker.outputs.deployment-url }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun

      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: site
          path: site/dist/

      - name: Deploy to Cloudflare Workers
        id: deploy-cloudflare-worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: ${{ github.ref == 'refs/heads/main' && 'deploy' || 'versions upload' }}
          workingDirectory: site/
